require 'yaml'
$data = YAML.load_file('autogenerated.yaml')

def parse string
    begin
        regex_match = /\[([a-z_]*)\]/.match(string)

        replace = $data[regex_match[1]].sample

        return string.gsub regex_match[0], parse(replace)
    rescue
        # raise
        return string
    end
end

100.times do
    puts "After #{parse $data['after'].sample}, #{parse $data['auto_targets'].sample} #{parse $data['targeted_effect'].sample}"
end
